### PR TITLE
Migration to latest zendframework/zend-form

### PR DESCRIPTION
**Pull request by boesing**
There is an issue with the `zendframework/zend-form` ^2.8.2 since the `FormElementManagerV2Polyfill` has reverse order of `injectFactory` which does not work with `zendframework/zend-mvc` `FormAnnotationBuilderFactory`.

### CODE REVIEW

**Comment by boesing** [comment]
Fixes #224

**Comment by boesing** [comment]
@weierophinney Would u mind this as hotfix like #72?

**Comment by boesing** [comment]
Well, actually we have to wait for zendframework/zend-form#143 before merging this.
After merging zendframework/zend-form#143, we have to raise version of `zendframework/zend-form` in `composer.json`.

**Comment by boesing** [comment]
@Xerkus could you have a look at this or probably ping someone who might be responsible? Would like to use those changes in production.

**Comment by weierophinney** [comment]
Thanks, @boesing

**Pull request merged**
