### PR TITLE
#185 Add zend-serializer to composer suggestion.

### PR DESCRIPTION
**Pull request by panvid**

### CODE REVIEW

**Review by froschdesign — APPROVED** [review]

**Comment by Xerkus** [comment]
I am not sure about this. It does not add any functionality to zend-mvc.

**Comment by froschdesign** [comment]
@Xerkus 
If an end-user wants to use the `LazyControllerAbstractFactory` in his application, then zend-serializer is required – but only there.
Therefore the hint / suggestion in the Composer file for this _soft_ dependency.

https://github.com/zendframework/zend-mvc/blob/fe43713dd6d251343139142ad680eab049edb6c6/src/Controller/LazyControllerAbstractFactory.php#L21
---
At the moment we have no reference or guide for the Composer file, but we use the suggest section since the introduction of Composer.

**Comment by Xerkus** [comment]
Neither `use` statement or magic `::class` constant require presence or existence of the referenced class. It is just a glorified string literal. I would argue this use case does not create soft dependency.

Controller requiring serializer adapter plugin manager as dependency would need to declare zend-serializer as a dependency on the other hand.

**Comment by froschdesign** [comment]
@Xerkus 
You are right! The factory doesn't use the serializer for running.

**Pull request closed without merging**
