### PR TITLE
Notice: Undefined variable: serviceLocator

### PR DESCRIPTION
**Pull request by michalbundyra**
@weierophinney here it is: fix for #148. I've added some tests, not sure if they are useful because as I can see this part is removed from v3. Let me know please what do you think. Thanks.

### CODE REVIEW

**Comment by weierophinney** [comment]
Okay, I see a couple of things.

First, as you note, the functionality is removed in zend-servicemanager v3, which means the tests fail if that version is installed.

Interestingly, zend-servicemanager-di, which is where we moved the functionality for the zend-mvc v3 release, _is_ tested against both versions, and contains the exact same functionality, albeit with different namespaces. Unfortunately, it contains the same typo. :frowning: I'll be doing a PR for that momentarily so we can get a working version in place.

My thought is that we do the following:
- Modify `DiAbstractServiceFactoryFactory` to extend `Zend\ServiceManager\Di\DiAbstractServiceFactoryFactory`
- Do the same for `DiAbstractServiceFactory` (have it extend the zend-servicemanager-di variant)
- Add a requirement in `composer.json` for zend-servicemanager-di

The above will solve the issue so that zend-mvc v2 continues to work, both against zend-servicemanager v2 and v3.

**Comment by michalbundyra** [comment]
@weierophinney I've updated my PR, please have a look. Thanks.

**Comment by weierophinney** [comment]
@webimpress I was working on similar changes, after reviewing this and zend-servicemanager-di.

I took your original changeset and was able to apply it against zend-servicemanager-di (with attribution, even; I used the `.patch` from this PR, edited it, and applied it to that component, which gives you credit for the commit), which fixed the related issue in that component. I've now opened #158, which:
- adds zend-servicemanager-di to the component requirements
- updates 4 of the DI-related factories to simply extend from the zend-servicemanager-di variants
- marks all 5 of the DI-related factories as deprecated via annotation

This approach is completely BC; the four I created as extensions were returning artifacts from the `Zend\ServiceManager\Di` namespace already, and the fifth now returns one of these extending classes, preserving inheritance.

Thanks for raising the issue, and for your patches!

**Comment by michalbundyra** [comment]
@weierophinney thank you, it's much better now, thanks :)

**Pull request closed without merging**
