### PR TITLE
update Redirect::toRoute() docblock as not only generate url

### PR DESCRIPTION
**Pull request by samsonasik**
but redirect based on url that generated based on given route.

### CODE REVIEW

**Comment by Maks3w** [comment]
I agree the original comment wasn't correct but the proposed is not enough precise. 

The function don't perform any redirection, it's generate a redirect response. 

This difference is important because with the proposed description developer may understand the request end and no more code will be executed (lije zf1 goToRouteAndExit) but it still require the developer to do something more with the generated response

**Comment by samsonasik** [comment]
So, it can be changed to: "Generate redirect response based on given route" ? what about `toUrl()`, need update too?

**Comment by Maks3w** [comment]
Yes to both questions

**Comment by samsonasik** [comment]
done, I've updated both

**Pull request merged**
