### PR TITLE
Fixes #78 : using uppercase for 'Application' service

### LINKED ISSUE #78: [dev-develop] using zend-servicemanager v3 got error: ": Unable to resolve service "application" to a factory"
This is the error:

```
( ! ) Fatal error: Uncaught Zend\ServiceManager\Exception\ServiceNotFoundException: Unable to resolve service "application" to a factory; are you certain you provided it during configuration? in /Users/samsonasik/www/zfskeleton25+/vendor/zendframework/zend-servicemanager/src/ServiceManager.php on line 623
( ! ) Zend\ServiceManager\Exception\ServiceNotFoundException: Unable to resolve service "application" to a factory; are you certain you provided it during configuration? in /Users/samsonasik/www/zfskeleton25+/vendor/zendframework/zend-servicemanager/src/ServiceManager.php on line 623
Call Stack
#   Time    Memory  Function    Location
1   0.0002  364392  {main}( )   .../index.php:0
2   0.1271  4606072 Zend\Mvc\Application->run( )    .../index.php:21
3   0.1343  5130872 Zend\Mvc\Application->completeRequest( )    .../Application.php:356
4   0.1343  5130872 Zend\EventManager\EventManager->triggerEvent( ) .../Application.php:384
5   0.1343  5130872 Zend\EventManager\EventManager->triggerListeners( ) .../EventManager.php:143
6   0.1343  5131448 Zend\Mvc\View\Http\DefaultRenderingStrategy->render( )  .../EventManager.php:271
7   0.1506  5831240 Zend\EventManager\EventManager->triggerEvent( ) .../DefaultRenderingStrategy.php:115
8   0.1506  5831240 Zend\EventManager\EventManager->triggerListeners( ) .../EventManager.php:143
9   0.1507  5832464 Zend\Mvc\View\Http\DefaultRenderingStrategy->render( )  .../EventManager.php:271
```

My composer.json:

```
        "zendframework/zendframework": "~2.5",
        "zendframework/zend-mvc": "dev-develop",
        "zendframework/zend-servicemanager": "dev-develop as 2.5",
        "zendframework/zend-eventmanager": "dev-develop as 2.5",
```

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes #78

### CODE REVIEW

**Comment by samsonasik** [comment]
It need to use uppercase when we require zend-servicemanager:v3

**Comment by weierophinney** [comment]
@samsonasik That's not really a fix. We need for both `application` and `Application` to resolve to ensure _user-land_ code continues to work. This will ensure the internals work, but it's the user-land code I'm more worried about.

**Comment by samsonasik** [comment]
@weierophinney I've added new entry for 'application' in the `ServiceListenerFactory` as it won't work with alias due Circular alias reference

**Comment by samsonasik** [comment]
should be ok now?

**Pull request merged**
