### PR TITLE
Make use of class names instead of strings for services

### PR DESCRIPTION
**Pull request by thexpand**
Related to issue: https://github.com/zendframework/zend-mvc/issues/186

### CODE REVIEW

**Comment by thexpand** [comment]
The Travis is failing on master, too. What can be done?

**Comment by geerteltink** [comment]
@thexpand Travis is failing on all `latest` builds, meaning it tests against all of the latest dependencies. So you could probably run `composer update` locally and should see the tests fail as well. It makes it easier to find the package that causes the error and fix it. And then you can still decide if you want to include the updated composer file or not.

**Comment by thexpand** [comment]
@xtreamwayz I have created a hotfix for this as a new PR https://github.com/zendframework/zend-mvc/pull/293
We'll be able to continue with the current PR only after merging the hotfix. Can you make a code review?

**Comment by boesing** [comment]
As already wrote in #294, we should close this PR in favor of #294.
Fixes required for passing unit tests are provided with #295.

If we close this, we can drop a lot of confusion with those Pull Requests I guess.

**Pull request closed without merging**
