### PR TITLE
Use callable type hint instead of a comment

### PR DESCRIPTION
**Pull request by jameskraai**
Use callable type hint instead of a comment

### CODE REVIEW

**Comment by Xerkus** [comment]
callable typehint is not available in php 5.6 which is the minimum supported version
https://github.com/zendframework/zend-mvc/blob/0cb6770856885ca916b44798e3ae37547a20b46e/composer.json#L20

**Comment by Ocramius** [comment]
`callable` is supported since PHP 5.4

**Comment by Xerkus** [comment]
It is. I confused it for iterable. Deleted comment immediately but mail already went out.

**Comment by Xerkus** [comment]
Adding a parameter typehint could be a BC break if someone extended and overrode the method. Merging it for the next major.
@jameskraai thank you

**Pull request closed without merging**
