### PR TITLE
Better ServiceLocatorAware deprecation

### PR DESCRIPTION
**Pull request by weierophinney**
This is a patch for fixing #87.

We were:
- injecting any service that _was not_ marked as `ServiceLocatorAware` but implemented `setServiceLocator()`, and
- injecting any service that _was_ marked `ServiceLocatorAware`, and
- emitting a deprecation notice in both cases.

The rationale was to allow backwards compatibility with existing implementations, while still messaging to users that they need to update their code not to rely on that.

This created a few problems, though:
- _Every_ controller inheriting from `AbstractController` now emits deprecation notices on instantiation.
- Developers who had implemented a `setServiceLocator()` method without implementing `ServiceLocatorAwareInterface` were now getting auto-injected with the service locator instance when they did not expect to.

This patch attempts to address those issues as follows:
- `ServiceManagerConfig` updates its service locator initializer to:
  - Inject non-plugin manager `ServiceLocatorAware` instances; in this situation, a deprecation notice _is_ emitted.
  - For `ServiceLocatorAware` plugin managers, it checks to see if a service locator is already composed. If not, it will inject it, but then emit a deprecation notice indicating that the service locator should be injected as a constructor parameter.
- `ControllerManager` updates its service locator initializer to:
  - For non-`ServiceLocatorAware` `AbstractController` implementations, it injects the service locator with no notices.
  - For all explicitly `ServiceLocatorAware` controllers, it injects the service locator _and_ emits a deprecation notice.
  - It no longer injects non-`ServiceLocatorAware` controllers that implement `setServiceLocator()` unless they extend `AbstractController`. This is fully backwards compatible.
- `AbstractController::getServiceLocator()` now emits a deprecation notice prior to returning the service locator instance. This is more appropriate, as we want to encourage users who rely on the service locator composition to upgrade.

Interestingly, this allows us to revert a number of changes that were made to the tests to mask deprecation notices, which helps solidify the argument that the original changes were indeed a backwards compatibility break, and that the new changes will address that situation.

### CODE REVIEW

**Comment by froschdesign** [comment]
Better! :+1:

**Comment by snapshotpl** [comment]
Much better! :+1:

**Comment by snapshotpl** [comment]
I see one case which allow users to use service locator in controllers without warning - by serviceLocator property. Are we should care about this? @weierophinney

**Comment by weierophinney** [comment]
@snapshotpl Too difficult to manage (we'd have to use property overloading, and that gets messy fast). Those users will feel the pain when they upgrade to zend-mvc v3 later, and it will be covered in the migration guide at that time.

**Comment by bgaillard** [comment]
@weierophinney Thanks, it works on our project now and we do not encounter the deprecated warning :+1:

**Comment by kevin-olbrich** [comment]
I encountered a problem regarding this deprecation:

Sample Code:

```
        $em = $this->getServiceLocator()->get('doctrine.entitymanager.orm_default');

        echo "test1".PHP_EOL;

        $machines = $em->getRepository('Main\Entity\DataMachines')->findAll();

        echo "test2".PHP_EOL;
        die("die here...");
```

Output:

> C:\secret>php public\index.php my-cli-job
> 
> Deprecated: You are retrieving the service locator from within the class CronJobs\Controller\SecretController. Please be aware that ServiceLocatorAwareInterface is deprecated and will be removed in version 3.0, along with the ServiceLocatorAwareInitializer. You will need to update your class to accept all dependencies at creation, either via constructor arguments or setters, and use a factory to perform the injections. in C:\secret\vendor\zendframework\zend-mvc\src\Controller\AbstractController.php on line 258
> test1
> 
> C:\secret>

The job silently dies when I call a function of doctrine.

**Comment by kevin-olbrich** [comment]
Problem fixed. Doctrine-only problem.
https://github.com/doctrine/DoctrineORMModule/issues/461

**Comment by chrisVdd** [comment]
Hi!

Could you please explain me how I can have this patch in my local project please ?
Thanks!

**Comment by froschdesign** [comment]
@chrisVdd 
Update the `Zend\Mvc` component per composer. For example:
- Version 2.7.10 for ZF2
- Version 3.0.3 for ZF3

**Pull request merged**
