### PR TITLE
use default console exception template instead of empty string

### PR DESCRIPTION
**Pull request by svycka**
this was overriding default template if no template is set.

also the method name and config option name 'exception_message' is not very clear what it is :D

### CODE REVIEW

**Comment by svycka** [comment]
@weierophinney I think this was introduced after your SM v3 refactor and merged into 2.7 is this desired behavior or bug? If not a bug then why we have default template and overriding anyway.

**Comment by snapshotpl** [comment]
@svycka can you add unit test to cover this bug?

**Comment by svycka** [comment]
in case this will not merged soon as a workaround I added default template from here https://github.com/zendframework/zend-mvc/blob/master/src/View/Console/ExceptionStrategy.php#L31-L44 to my local config like this:

```
return [
    'console' => [
        'view_manager' => [
            'exception_message' => '
======================================================================
   The application has thrown an exception!
======================================================================
 :className
 :message
----------------------------------------------------------------------
:file::line
:stack
======================================================================
   Previous Exception(s):
:previous

',
        ]
    ]
];
```

> @svycka can you add unit test to cover this bug?

@snapshotpl not sure but maybe if really needed

**Comment by svycka** [comment]
@snapshotpl is it ok?

**Comment by svycka** [comment]
@weierophinney this bug also is a BC break and maybe can be fixed faster?

**Comment by weierophinney** [comment]
@svycka Merged, and tagged 2.7.5. Can you do a similar PR against zend-mvc-console, please?

**Comment by svycka** [comment]
@weierophinney done https://github.com/zendframework/zend-mvc-console/pull/5

**Pull request merged**
