### PR TITLE
Hops not used because of unset in get method.

### PR DESCRIPTION
**Pull request by riznmage**
Calling getMessagesFromContainer() results in clearing the messages in the session, regarding the hops, defined when adding a message.

### CODE REVIEW

**Comment by weierophinney** [comment]
Please provide unit tests for this; right now I _still_ don't understand what the expectations are. Unit tests will clarify that.

Additionally, please look at the travis-ci output, and run `php-cs-fixer`; you have CS issues currently.

**Comment by riznmage** [comment]
When hops are used, the key gets expired on the first request, no matter what number is used for the hops.

**Comment by weierophinney** [comment]
@riznmage Please write _tests_ for that behavior, then.

Tests help us:
- understand the expectations properly.
- document the expectations for others.
- ensure that future changes do not _break_ those expectations.

**Comment by riznmage** [comment]
The Travis CI build failed because of other tests, not related to the issue. You can check https://travis-ci.org/zendframework/zend-mvc/jobs/66870601

A test cannot be written, since a second request is needed to be made to test this. Basically, the expected behavior is this:
1. In a controller action, a message is set:
   `$this->flashMessenger()->addMessage("Message text", FlashMessenger::NAMESPACE_ERROR, 2);`
   This message uses 2 hops, which means that it will be kept for 2 more requests in the session.
2. A redirect is made from the same action:
   `return $this->redirect()->toRoute("someRouteName");`
   On the redirected page, the message is available.
3. Then a new request is made either by the user, or via AJAX/ESI. Judging by the value of the hops (2), the message should be available on this page, too, but it isn't.

**Comment by Maks3w** [comment]
@riznmage Travis-CI it's failing because the PR does not follow the CS guidelines

https://travis-ci.org/zendframework/zend-mvc/jobs/66870601#L433

Execute `./vendor/bin/php-cs-fixer fix -v` in the project root

**Comment by weierophinney** [comment]
> A test cannot be written, since a second request is needed to be made to test this.

You can mock the session manager in order to emulate multiple requests.

**Comment by Maks3w** [comment]
@riznmage Your last commit is erroneus. You have to execute the command in your local machine and don't modify travis configuration which is out of the scope.

**Comment by riznmage** [comment]
@weierophinney I haven't writter a unit test so far. I'm just reporting a bug. Read https://github.com/zendframework/zend-mvc/pull/9#issuecomment-112082949 thoroughly and you will get what I'm talking about.

**Comment by weierophinney** [comment]
@riznmage Please review [my earlier comment](https://github.com/zendframework/zend-mvc/pull/9#issuecomment-112068654). I'm asking you to write a test so that we can understand the behavior expected _and_ ensure that once corrected it _stays_ corrected later.

If you need assistance writing the unit test, you can jump into the #zftalk.dev channel on Freenode IRC and ask.

**Comment by riznmage** [comment]
> Execute ./vendor/bin/php-cs-fixer fix -v in the project root
> How exactly? @Maks3w

**Comment by riznmage** [comment]
Okay.. it seems to be a mistake that I made. I was using `getMessages()` instead of `getCurrentMessages()`. Can you explain me what is the difference between these two? Why is `getMessages()` clearing the messages from the session container?

**Comment by weierophinney** [comment]
`getMessages()` is the one to use when accessing messages set in the _previous_ request (which is the general reason for using FlashMessenger). `getCurrentMessages()` is the method to use when you want access to messages set during the _current_ request.

`getMessages()` will clear the container of any expired messages, so that the next invocation will only retrieve those that still have request hops available (which is what the `hops` setting is for); that's likely the behavior you are seeing.

**Pull request closed without merging**
