### PR TITLE
Fix @return comment of getRequest()  for correct auto completion

### PR DESCRIPTION
**Pull request by marinovdf**

### CODE REVIEW

**Comment by Maks3w** [comment]
`HttpRequest` is an implementation of `Zend\Stdlib\RequestInterface`

**Comment by marinovdf** [comment]
Yes, i understand. 
PhpStorm says "Method `getPost` not found in class `\Zend\Stdlib\RequestInterface`", if I write `$this->getRequest()->getPost()` in my controller. Maybe it's bug of PhpStorm.
Sorry for my English.

**Comment by manuakasam** [comment]
There is no bug.

The implementation by ZF2 simply offers much more than the interface is
requiring. That is not an error or bug at all.

What you can do is this:

```
/** @var \Zend\Http\PhpEnvironment\Request $request */
$request = $this->getRequest();
```

And with this you'll then have full IDE support of all the functions :)

marinovdf notifications@github.com schrieb am Di., 6. Okt. 2015 um
12:44 Uhr:

**Comment by Maks3w** [comment]
IIRC its possible add the magic `@method` annotation at class level. However for to be purist the best option is use the `instanceof` operator with the return of `getRequest` and avoid accidental PHP Errors.

**Pull request closed without merging**
